In [1]:
import torch

- $Tensor.scatter_(dim, index, src, *, reduce=None)$
    - Writes values from src to self based on index tensor and dim. 
    - For dimension == dim, index values are selected.
    - For dimension != dim, src values in src are selected. 
    

- It is useful for one hot encoding from (Batch_size, 1) into (Batch_size, N)

In [12]:
labels = torch.tensor([
    [2], [0], [1], [3]])

print(labels.shape) # (Batch_size, 1)

one_hot = torch.zeros(4, 4)

one_hot.scatter_(dim=1, index=labels, value=1)

print(one_hot)


torch.Size([4, 1])
tensor([[0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.]])


- Convert multiple selected indices into the multi class label form

In [17]:
labels = torch.tensor([
    [2, 0], [0, 1], [1, 1], [3, 3]])

print(labels.shape) # (Batch_size, 2)

one_hot = torch.zeros(4, 4)

one_hot.scatter_(dim=1, index=labels, value=1)

print(one_hot)


torch.Size([4, 2])
tensor([[1., 0., 1., 0.],
        [1., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 0., 1.]])


- TopK Masking

In [22]:
logits = torch.tensor([[1.2, 5.0, 0.1, 4.2, 0.5],
                       [0.2, 1.1, 6.3, 0.5, 3.1]])

_, topk = torch.topk(logits, k=2, dim=1)

print(topk)

mask = torch.zeros_like(logits)
mask.scatter_(dim=-1, index=topk, value=1)

print(mask)

print(logits * mask)

tensor([[1, 3],
        [2, 4]])
tensor([[0., 1., 0., 1., 0.],
        [0., 0., 1., 0., 1.]])
tensor([[0.0000, 5.0000, 0.0000, 4.2000, 0.0000],
        [0.0000, 0.0000, 6.3000, 0.0000, 3.1000]])
